<?php
if (isset($_POST['texto'])) {
    $texto = $_POST['texto'];
    $acentos = array(
        0 => 'á',
        1 => 'é',
        2 => 'í',
        3 => 'ó',
        4 => 'ú',
        5 => 'Á',
        6 => 'É',
        7 => 'Í',
        8 => 'Ó',
        9 => 'Ú',
        10 => 'â',
        11 => 'ê',
        12 => 'ô',
        13 => 'Â',
        14 => 'Ê',
        15 => 'Ô',
        16 => 'ã',
        17 => 'õ',
        18 => 'Ã',
        19 => 'Õ',
        20 => 'à',
        21 => 'À',
        22 => 'ç',
        23 => 'Ç',
        24 => 'ü',
        25 => 'Ü',
        26 => '®',
        27 => '©',
        28 => 'ª',
        29 => 'º',
        30 => 'º',
        31 => '–',
        32 => '—',
        33 => '¯',
        34 => '•',
        35 => '°',
    );
    $codigo = array(
        0 => '&amp;aacute;',
        1 => '&amp;eacute;',
        2 => '&amp;iacute;',
        3 => '&amp;oacute;',
        4 => '&amp;uacute;',
        5 => '&amp;Aacute;',
        6 => '&amp;Eacute;',
        7 => '&amp;Iacute;',
        8 => '&amp;Oacute;',
        9 => '&amp;Uacute;',
        10 => '&amp;acirc;',
        11 => '&amp;ecirc;',
        12 => '&amp;ocirc;',
        13 => '&amp;Acirc;',
        14 => '&amp;Ecirc;',
        15 => '&amp;Ocirc;',
        16 => '&amp;atilde;',
        17 => '&amp;otilde;',
        18 => '&amp;Atilde;',
        19 => '&amp;Otilde;',
        20 => '&amp;agrave;',
        21 => '&amp;Agrave;',
        22 => '&amp;ccedil;',
        23 => '&amp;Ccedil;',
        24 => '&amp;uuml;',
        25 => '&amp;Uuml;',
        26 => '&amp;reg;',
        27 => '&amp;copy;',
        28 => '&amp;ordf;',
        29 => '&amp;ordm;',
        30 => '&amp;deg;',
        31 => '&amp;ndash;',
        32 => '&amp;mdash;',
        33 => '&amp;macr;',
        34 => '&amp;bull;',
        35 => '&amp;#176;'
    );
    $acentoJs = array(
        'á' => '&#92;u00e1',
        'à' => '&#92;u00e0',
        'â' => '&#92;u00e2',
        'ã' => '&#92;u00e3',
        'ä' => '&#92;u00e4',
        'Á' => '&#92;u00c1',
        'À' => '&#92;u00c0',
        'Â' => '&#92;u00c2',
        'Ã' => '&#92;u00c3',
        'Ä' => '&#92;u00c4',
        'é' => '&#92;u00e9',
        'è' => '&#92;u00e8',
        'ê' => '&#92;u00ea',
        'ê' => '&#92;u00ea',
        'É' => '&#92;u00c9',
        'È' => '&#92;u00c8',
        'Ê' => '&#92;u00ca',
        'Ë' => '&#92;u00cb',
        'í' => '&#92;u00ed',
        'ì' => '&#92;u00ec',
        'î' => '&#92;u00ee',
        'ï' => '&#92;u00ef',
        'Í' => '&#92;u00cd',
        'Ì' => '&#92;u00cc',
        'Î' => '&#92;u00ce',
        'Ï' => '&#92;u00cf',
        'ó' => '&#92;u00f3',
        'ò' => '&#92;u00f2',
        'ô' => '&#92;u00f4',
        'õ' => '&#92;u00f5',
        'ö' => '&#92;u00f6',
        'Ó' => '&#92;u00d3',
        'Ò' => '&#92;u00d2',
        'Ô' => '&#92;u00d4',
        'Õ' => '&#92;u00d5',
        'Ö' => '&#92;u00d6',
        'ú' => '&#92;u00fa',
        'ù' => '&#92;u00f9',
        'û' => '&#92;u00fb',
        'ü' => '&#92;u00fc',
        'Ú' => '&#92;u00da',
        'Ù' => '&#92;u00d9',
        'Û' => '&#92;u00db',
        'ç' => '&#92;u00e7',
        'Ç' => '&#92;u00c7',
        'ñ' => '&#92;u00f1',
        'Ñ' => '&#92;u00d1',        
        "'" => '&#92;u0027'
    );
    $acentoJsRev = array(
        'á' => '\u00e1',
        'à' => '\u00e0',
        'â' => '\u00e2',
        'ã' => '\u00e3',
        'ä' => '\u00e4',
        'Á' => '\u00c1',
        'À' => '\u00c0',
        'Â' => '\u00c2',
        'Ã' => '\u00c3',
        'Ä' => '\u00c4',
        'é' => '\u00e9',
        'è' => '\u00e8',
        'ê' => '\u00ea',
        'ê' => '\u00ea',
        'É' => '\u00c9',
        'È' => '\u00c8',
        'Ê' => '\u00ca',
        'Ë' => '\u00cb',
        'í' => '\u00ed',
        'ì' => '\u00ec',
        'î' => '\u00ee',
        'ï' => '\u00ef',
        'Í' => '\u00cd',
        'Ì' => '\u00cc',
        'Î' => '\u00ce',
        'Ï' => '\u00cf',
        'ó' => '\u00f3',
        'ò' => '\u00f2',
        'ô' => '\u00f4',
        'õ' => '\u00f5',
        'ö' => '\u00f6',
        'Ó' => '\u00d3',
        'Ò' => '\u00d2',
        'Ô' => '\u00d4',
        'Õ' => '\u00d5',
        'Ö' => '\u00d6',
        'ú' => '\u00fa',
        'ù' => '\u00f9',
        'û' => '\u00fb',
        'ü' => '\u00fc',
        'Ú' => '\u00da',
        'Ù' => '\u00d9',
        'Û' => '\u00db',
        'ç' => '\u00e7',
        'Ç' => '\u00c7',
        'ñ' => '\u00f1',
        'Ñ' => '\u00d1',        
        "'" => '\u0027'
    );
    if ((!isset($_POST['tipo']) || empty($_POST['tipo'])) || $_POST['tipo'] == 'html') {
        for ($x = 0; $x < 36; $x++) {
            //echo $acentos[$x]." - ".$codigo[$x]."<br>";
            $texto = str_replace($acentos[$x], $codigo[$x], $texto);
        }
    } else if ($_POST['tipo'] == 'js') {
        foreach ($acentoJs as $pos => $valor)
            $texto = str_replace($pos, $valor, $texto);
    }else if ($_POST['tipo'] == 'jsrev') {        
        foreach ($acentoJsRev as $pos => $valor){
            $texto = str_replace($valor, $pos, $texto);
        }
    }
}
?>

<center><form method="post" action="index.php">
        <textarea name="texto" cols="60" rows="20"><?php if (!empty($texto)) echo stripcslashes($texto) ?></textarea><br/>
        <input type="radio" name="tipo" value="html" <?php echo (isset($_POST['tipo']) && $_POST['tipo'] == 'html') ? "checked" : ''; ?> /> html <input type="radio" name="tipo" value="js" <?php echo (isset($_POST['tipo']) && $_POST['tipo'] == 'js') ? "checked" : ''; ?> /> JS <input type="radio" name="tipo" value="jsrev" <?php echo (isset($_POST['tipo']) && $_POST['tipo'] == 'jsrev') ? "checked" : ''; ?> /> JS reverso<br/>
        <input type="submit" value="Trocar acentos"/>

    </form></center>

